/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Entidades.Autor;
import Entidades.Usuario;
import comunicacion.IOperacion;
import comunicacion.SOperacion;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class pMostrarCosto extends javax.swing.JFrame {

    private final IOperacion op;
    private Autor autor;
    private int nPaginas;
    private String titulo;
    private int paginaInicial;
    private String tipoPublicacion;
    private float tamMegas;
    private String tipoPago;
    private String estado;
    private int click;
    private Usuario usuario;

    /**
     * Creates new form pTipoPublicacion
     *
     * @param costo
     * @param precioVenta
     * @param tipoPago
     * @param tipoPublicacion
     * @param nPaginas
     * @param user
     */
    public pMostrarCosto(float costo, float precioVenta, String tipoPago, String tipoPublicacion, int nPaginas, Usuario user) {
        initComponents();
        op = SOperacion.getOperacion();
        this.estado = "Pagado";
        this.usuario = user;
        this.tipoPago = tipoPago;
        this.tipoPublicacion = tipoPublicacion;
        this.txtCosto.setText(String.valueOf(costo));
        this.txtPrecio.setText(String.valueOf(precioVenta));
        this.nPaginas = nPaginas;
        String fechas[] = obtenerFechas();
        this.txtFechaInicio.setText(fechas[0]);
        this.txtFechaEntrega.setText(fechas[1]);
        this.txtMedioPago.setText(tipoPago);
        if (tipoPublicacion.equals("Digital")) {
            ocultarFechas();
        }
        ocultarBoton(costo);
    }

    private void ocultarFechas() {
        this.lblFechaInicio.setVisible(false);
        this.txtFechaInicio.setVisible(false);
        this.lblFechaEntrega.setVisible(false);
        this.txtFechaEntrega.setVisible(false);
    }

    public void sendDataFisico(Autor autor, String titulo, int paginaInicial) {
        this.autor = autor;
        this.titulo = titulo;
        this.paginaInicial = paginaInicial;
    }

    public void sendDataDigital(Autor autor, String titulo, float tamMegas) {
        this.autor = autor;
        this.titulo = titulo;
        this.tamMegas = tamMegas;
    }

    private void ocultarBoton(float costo) {
        if (costo < 1000) {
            btnEstado.setVisible(true);
        } else {
            btnEstado.setVisible(false);
        }
    }

    private void pagarMitad(int click) {
        float costo = Float.parseFloat(txtCosto.getText());
        estado = "Pendiente por pagar";
        costo = costo / 2;
        txtCosto.setText(String.valueOf(costo));
        click = 1;
    }

    private String[] obtenerFechas() {
        return op.calcularFechas(nPaginas);
    }

    private void aceptarCosto() {
        if (tipoPublicacion.equals("Fisico")) {
            String fechas[] = obtenerFechas();
            op.registrarPublicacionTipoFisico(autor, nPaginas, titulo, paginaInicial, tipoPublicacion, tipoPago,
                    fechas[0], fechas[1], estado);
        } else {
            op.registrarPublicacionTipoDigital(autor, nPaginas, titulo, tipoPublicacion, tamMegas, tipoPago, estado);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCosto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        txtMedioPago = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaEntrega = new javax.swing.JTextField();
        btnEstado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("El costo de la publicación es:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Costo:");

        btnAceptar.setBackground(new java.awt.Color(0, 204, 204));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        btnAceptar.setText("Aceptar cotización");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCosto.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio de venta:");

        txtPrecio.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Medio de pago:");

        lblFechaInicio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaInicio.setText("Fecha de inicio:");

        lblFechaEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFechaEntrega.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaEntrega.setText("Fecha de entrega:");

        txtMedioPago.setEnabled(false);

        txtFechaInicio.setEnabled(false);

        txtFechaEntrega.setEnabled(false);

        btnEstado.setBackground(new java.awt.Color(204, 204, 204));
        btnEstado.setForeground(new java.awt.Color(0, 0, 0));
        btnEstado.setText("pagar mitad");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaInicio)
                    .addComponent(lblFechaEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCosto)
                    .addComponent(txtPrecio)
                    .addComponent(txtMedioPago)
                    .addComponent(txtFechaInicio)
                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(26, 26, 26)
                .addComponent(btnCancelar)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEntrega)
                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "Necesitas iniciar sesion\n para registrar una publicacion");
        } else {
            aceptarCosto();
        }
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        pagarMitad(click);
        btnEstado.setEnabled(false);
    }//GEN-LAST:event_btnEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtMedioPago;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
